/* ALL ACTIONS TO USE */

const GET_USERINFO_REQUEST = "GET_USERINFO_REQUEST";
const GET_USERINFO_SUCCESS = "GET_USERINFO_SUCCESS";
const GET_USERINFO_ERROR = "GET_USERINFO_ERROR";

const POST_USERINFO_REQUEST = "POST_USERINFO_REQUEST";
const POST_USERINFO_SUCCESS = "POST_USERINFO_SUCCESS";
const POST_USERINFO_ERROR = "POST_USERINFO_ERROR";

const SET_LOGIN_STATE = "SET_LOGIN_STATE";

export {
	GET_USERINFO_REQUEST,
	GET_USERINFO_SUCCESS,
	GET_USERINFO_ERROR,
	POST_USERINFO_REQUEST,
	POST_USERINFO_SUCCESS,
	POST_USERINFO_ERROR,
	SET_LOGIN_STATE,
};
